//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminsys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Xml.Linq;

    public partial class TBLUserInfo
    {
        [Display(Name = "Id")]
        public int IdUs { get; set; }
        [Display(Name = "Username")]
        public string UsernameUS { get; set; }
        [Display(Name = "Password")]
        public string PasswordUS { get; set; }
    }
}
